[DEV-23] write a simple authorization service using jwt, postgres, id…
ENVILOUP/Videos pull request #3
Opened 2024-11-16 16:11 UTC by BloodyAngel22

2024-11-17 13:36 UTC, jojopko commented
Добавь проксирование через nginx, как я делал в [тут](https://github.com/ENVILOUP/Videos/pull/2/files#diff-d7a00807e6244719869cc4da473d13e17eb114396a164c3fd0f2e3ffd75420cf). Запросики должны отпарвлять на урл типа такого: `http//enviloup.local/auth/`

2024-11-17 13:40 UTC, jojopko commented on Authorization/app/docker-compose.yml
Тут должно быть только `app`. Версию тоже удали, ее в новых композах не нужно ставить. Считай, что тут ты описываешь продакшн, базы в продакшне не должна быть в контейнере

2024-11-17 13:44 UTC, jojopko commented on Authorization/app/docker-compose.debug.yml
Переименуй в docker-compose.override.yml. Он так будет автоматически при docker compose up мержить docker-compose.yml и docker-compose.override.yml (можешь в feature/dev-25 посмотреть как это работает). Это будет аналогично такой команде docker compose -f docker-compose.yml docker-compose.override.yml up

Вот дока по теме мержинга докер композов: https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/

2024-11-17 13:46 UTC, jojopko commented on Authorization/app/docker-compose.debug.yml
Да, короче в этом файле можно описывать локальную конфигурацию приложения: дополнительные настройки не для прода или нужные для локального запуска контейнеры (типа базы)

2024-11-17 13:50 UTC, jojopko commented on Authorization/app/.vscode/tasks.json
в .gitignore

2024-11-17 13:50 UTC, jojopko commented on Authorization/app/.vscode/launch.json
в .gitignore

2024-12-29 16:06 UTC, jojopko commented
README напиши обязательно

2025-01-04 09:18 UTC, jojopko commented
`nginx/`, `Dockerfile`, `docker-compose.yml` не являются частью приложения. Они не должны быть в `app/`. Все это дело на уровень сервиса нужно `/Authorization/`

2025-01-05 11:58 UTC, jojopko requested changes

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			return Ok(new { AccessToken = newAccessToken, RefreshToken = newRefreshToken });
1. Старый refresh токен мы не удаляем?
2. Можем мы воспользоваться старым refresh токеном для получения access токена?
3. newRefreshTokenEntity - это просто запись в базе user-refresh_token?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			var refreshToken = await _dbContext.RefreshTokens.FirstOrDefaultAsync(rt => rt.Token == model.RefreshToken);
Я сначала не понял, что значит `rt`, напиши понятнее - `refreshToken`. Что возвращается by default? null?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +		[Authorize]
Как этот атрибут понимает, что юзер авторизован?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Controllers/SecretController.cs
Это для чего? Просто тест? Если так - удали потом, а лучше напиши его явно как тест через Xunit, например. Второй вариант предпочтительнее, но пока можно забить, хотя тестирование обязательно нужно вводить

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +		public static void MapCustomHealthChecks(this IEndpointRouteBuilder endpoints)
Мне кажется странным выносить health check в middleware. Почему ты так сделал, а не использовал контроллер?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +				endpoints.MapGet("/", () => "Enviloup. void sex");
Отсылки прикольно, но тут мне кажется ей не место)

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +		}
Когда этот код выполняется и сколько раз?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Extensions/ServiceExtensions.cs
> +			var key = configuration["JWT:Key"] ?? throw new InvalidOperationException("JWT:Key not found");
Это из appsettings.json? Если так - его нельзя там хранить. Это секретная информация, которая должна лежать как минимум в env или kubernetes secret, но не в репозитории в открытом виде

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Extensions/ServiceExtensions.cs
> +		public static void ConfigureHealthChecks(this IServiceCollection services, string connectionString)
Поясни, что это делает?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Migrations/20241116135427_Init.Designer.cs
Мне кажется нужно схлопнуть миграции в одну, так как это одна фича по факту. Миграцию новую создавать имеет смысл в новом MR или если она изменяет что-то что уже есть на проде.

Можно их все удалить и сделать `dotnet ef migrations add InitialCreate` потом `dotnet ef database update` - мне так гпт говорит

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/AppDbContext.cs
> +				.HasOne(rt => rt.User)
напиши понятнее

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/LoginModel.cs
> +		public string Password { get; set; } = null!;
Объясни для чего `null!`? Почему ты не написал `string?` или `String.Empty`. Выглядит как костыль закрывающий warning в ide

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/RefreshToken.cs
> +		public IdentityUser User { get; set; } = null!;
Выше написал про `null!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/RefreshTokenModel.cs
> +        public string RefreshToken { get; set; } = null!;
Выше написал про `null!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/RegisterModel.cs
> +		public string Email { get; set; } = null!;
Выше написал про `null!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Models/RevokeTokenModel.cs
> +        public string RefreshToken { get; set; } = null!;
Выше написал про `null!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Program.cs
> +builder.Services.ConfigureHealthChecks(connectionString!);
Это видимо тоже тема с `null!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Properties/launchSettings.json
Для чего этот файл?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Services/JWTService.cs
> +				new Claim(ClaimTypes.Name, user.UserName!)
`user.UserName!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Services/JWTService.cs
> +			var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT:Key"]!));
`_configuration["JWT:Key"]!`

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/Services/JWTService.cs
> +			var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT:Key"]!));
Также напоминаю про безопасность

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/app.csproj
> +    <Nullable>enable</Nullable>
Это наверное для `null!` включил?

2025-01-05 11:58 UTC, jojopko commented on Authorization/app/appsettings.json
Как я могу поменять уровень логирования без изменения в коде?

2025-01-05 11:58 UTC, jojopko commented on Authorization/nginx/conf.d/authorization-app.conf
> +				proxy_set_header X-Forwarded-Prefix auth/;
Форматирование поехало

2025-01-06 08:30 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			int windowTimeHours = 1; //оконное время, чтобы можно было обновить refresh token и не давать пользователю форму авторизации
Как я понял: если пользователь не взаимодействовал с сервисом более часа - его токен автоматически протухает, но если он активно пользуется им, на каждый запрос он добавляет еще час к времени жизни токена?

1. Что будет если я буду отправлять 100500 запросов на refresh-token/? Будет увеличено время жизни токена на 1 * 100500 часов?
2. Почему бэк должен заботиться о пользователе? Этот токен будет храниться скорее всего в куке, фронт должен сам его обновлять, если он протухает, разве нет?

2025-01-06 08:38 UTC, jojopko requested changes

2025-01-06 08:38 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			if (refreshToken.ExpiryDate <= DateTime.UtcNow)
DateTime.UtcNow может стрельнуть. Либо мы везде используем UTC, либо получаем текущую таймзону

2025-01-06 08:38 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			int windowTimeHours = 1; //оконное время, чтобы можно было обновить refresh token и не давать пользователю форму авторизации
Комментарии - это плохо. Если ты написал комментарий, значит плохо написал код. Этот код не такой сложный чтобы тут был коммент.

Еще тут используется магическое значение `1` - из контекста понятно что это, но надо вынести в константу, а если мы предплогаем, что это значение может изменяться - в конфигурацию

2025-01-06 08:38 UTC, jojopko commented on Authorization/app/Controllers/AuthController.cs
> +			var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time") ?? throw new InvalidOperationException("Time zone not found.");
Почему выше UTC, а тут Russian Standard Time? А если сервер в Германии будет UTC+1?

2025-01-06 08:46 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			int windowTimeHours = 1; //оконное время, чтобы можно было обновить refresh token и не давать пользователю форму авторизации
1. Время жизни токена не будет увеличено на 1 * 100500 часов. Я добавил оконное время, чтобы можно было обновить refresh token, иначе refresh token вообще бы нельзя было обновить. Сейчас получается так, что выдается час времени после протухания refresh токена, чтобы его можно было обновить на новый.
2. А в чем тут забота? Да, он будет храниться на фронте в куках и скорее всего будет таймер, который будет раз в полчаса отсылать refresh, чтобы получить новый access токен. Вместе с этим таймером и обновиться refresh токен, когда подойдет время его протухания

2025-01-06 08:47 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			int windowTimeHours = 1; //оконное время, чтобы можно было обновить refresh token и не давать пользователю форму авторизации
Время меняться не будет. Тогда вынесу в константу. Комментарий уберу.

2025-01-06 08:49 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time") ?? throw new InvalidOperationException("Time zone not found.");
Если сервер будет в Германии, то да, проблема. Заметил трабл, что в бд сохраняется время без учета временной зоны.

2025-01-06 08:50 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			if (refreshToken.ExpiryDate <= DateTime.UtcNow)
Лучше всего UTC. В чем проблема написал в коммите и ниже.

2025-01-06 08:57 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			var refreshToken = await _dbContext.RefreshTokens.FirstOrDefaultAsync(rt => rt.Token == model.RefreshToken);
Поменял. FirstOrDefaultAsync - возвращает значение или null, если не нашел в бд.

2025-01-06 09:02 UTC, BloodyAngel22 commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +		public static void MapCustomHealthChecks(this IEndpointRouteBuilder endpoints)
Middleware работает на более низком уровне, чем контроллеры. Это позволяет быстрее обрабатывать запросы, т.к. не требуется проходить через весь pipeline обработки запроса, включая маршрутизацию и контроллеры.

2025-01-06 09:05 UTC, BloodyAngel22 commented on Authorization/app/Controllers/SecretController.cs
Это проверка после применения access токена, чтобы получить данные из контроллера. Вообще, как тест того, что авторизация прошла успешно.

2025-01-06 09:05 UTC, BloodyAngel22 commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +				endpoints.MapGet("/", () => "Enviloup. void sex");
Убрал

2025-01-06 09:06 UTC, BloodyAngel22 commented on Authorization/app/Extensions/MiddlewareExtensions.cs
> +		}
Выполняется каждый раз при запуске приложения. Если миграции уже применены, то отпишет в логи, что уже применять нечего

2025-01-06 09:07 UTC, BloodyAngel22 commented on Authorization/app/Extensions/ServiceExtensions.cs
> +			var key = configuration["JWT:Key"] ?? throw new InvalidOperationException("JWT:Key not found");
Уже лежит в переменных среды

2025-01-06 09:08 UTC, BloodyAngel22 commented on Authorization/app/Extensions/ServiceExtensions.cs
> +		public static void ConfigureHealthChecks(this IServiceCollection services, string connectionString)
Что именно? AddDefaultTokenProviders() или ConfigureHealthChecks?

2025-01-06 09:29 UTC, BloodyAngel22 commented on Authorization/app/Models/LoginModel.cs
> +		public string Password { get; set; } = null!;
Да, тут я подавляю предупреждение о работе с пустой строкой, говоря, что обязательно данные там будут. Заменил на required и добавил атрибут Required для проверки данных.  Если написать через string?, то может получиться ситуация, когда пользователь в теле запроса не передает данные. Обычно используется при работе с NoSQL бд. String.Empty просто объявляет пустую строку.

2025-01-06 09:30 UTC, BloodyAngel22 commented on Authorization/app/Program.cs
> +builder.Services.ConfigureHealthChecks(connectionString!);
Да, верно. Подавил ошибку. Теперь добавил проверку и выкидываю исключение, если пустая строка

2025-01-06 09:33 UTC, BloodyAngel22 commented on Authorization/app/Properties/launchSettings.json
Настройка среды разработки, автозапуск браузера, поддержка нескольких профилей(http и https), переменные среды

2025-01-06 09:44 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time") ?? throw new InvalidOperationException("Time zone not found.");
Можно тогда в зависимости от системы указывать временную зону.

2025-01-06 09:51 UTC, BloodyAngel22 commented on Authorization/app/Controllers/AuthController.cs
> +			var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time") ?? throw new InvalidOperationException("Time zone not found.");
Все. Перенес на UTC везде, чтобы не было проблем

2025-01-06 10:04 UTC, jojopko commented on Authorization/app/Extensions/ServiceExtensions.cs
> +		public static void ConfigureHealthChecks(this IServiceCollection services, string connectionString)
Вчера у тебя спросил, уже понял

2025-01-06 10:19 UTC, jojopko requested changes

2025-01-06 10:19 UTC, jojopko commented on Authorization/README.md
> +   docker-compose build
Замени на `docker compose`. `docker-compose` - это легаси

2025-01-06 10:19 UTC, jojopko commented on Authorization/app/Extensions/ExceptionMiddleware.cs
> +				_logger.LogError($"Ошибка: {ex.Message}");
'speak english'
https://www.youtube.com/watch?v=zirpPi7Ntyo

2025-01-06 10:19 UTC, jojopko commented on Authorization/app/Extensions/ExceptionMiddleware.cs
> +				// DetailedMessage = exception.Message // Уберите, если не хотите показывать детали.
Убери это

2025-01-06 10:19 UTC, jojopko commented on Authorization/app/Models/LoginModel.cs
> +        public required string Username { get; set; }
Для чего `[Required]` если уже поле `required`

2025-01-06 10:19 UTC, jojopko commented on Authorization/app/Models/RefreshToken.cs
> +		public required string UserId { get; set; }
Почему тут нет `[Required]`?

2025-01-08 07:11 UTC, BloodyAngel22 commented on Authorization/app/Models/LoginModel.cs
> +        public required string Username { get; set; }
Атрибут `[Required]` используется для проверки входящих данных на этапе выполнения, а модификатор `required` обеспечивает проверку на этапе компиляции. Они решают разные задачи и дополняют друг друга.  Благодаря `[Required]`  можно делать проверки !ModelState.IsValid

2025-01-08 07:13 UTC, BloodyAngel22 commented on Authorization/app/Models/RefreshToken.cs
> +		public required string UserId { get; set; }
Потому что я использую RefreshToken для добавления в бд и у меня нет контроллеров, которые принимают объект RefreshToken для проверки.

2025-01-08 07:13 UTC, BloodyAngel22 commented on Authorization/app/Models/RefreshToken.cs
> +		public required string UserId { get; set; }
Выше описал разницу required и [Required]

2025-01-08 10:03 UTC, jojopko approved these changes

2025-01-08 10:04 UTC, merged